### ISSUE TITLE
Create default folder structure

### ISSUE THREAD

**Issue by alexdodonov** [alexdodonov/mezon-cli#1]
```bash
mezon create fs
```
Directory structure must be:

./%project name%/Actions
./%project name%/ListBuilderAdapters
./%project name%/Logic
./%project name%/Middleware
./%project name%/Models
./%project name%/Presenters
./%project name%/Repositories
./%project name%/Tables
./%project name%/Views
./Conf
./Include/Js
./Include/Php
./Res/Images
./Testing/Selenium
./Testing/Unit

Before creating directories %project name% must be prompted

In the root of the each directory empty file index.html must be created to prevent direct access to this directory.

**Comment by lolix-notepad** [comment]
Hello @alexdodonov.

I have another question, the empty index.html file is like this?
```
./%project name%/Actions/index.html
./%project name%/ListBuilderAdapters/index.html
./%project name%/Logic/index.html

... And so on
```

In every folder.

**Comment by alexdodonov** [comment]
Yes

**Comment by alexdodonov** [comment]
Implemented in the v.1.0.4

@lolix-notepad Thanks! BTW you can invite your friends or collegues to join the project )

**Comment by lolix-notepad** [comment]
> Implemented in the v.1.0.4
> 
> @lolix-notepad Thanks! BTW you can invite your friends or collegues to join the project )

Ok, I'll invite them.
