### ISSUE TITLE
Questions about the verbs and entities

### ISSUE THREAD

**Issue by lolix-notepad** [alexdodonov/mezon-cli#3]
Hello, a question. What is inside of `Application.php?`

**Comment by lolix-notepad** [comment]
```php
<?php
namespace Mezon\Cli\Entities;

use Mezon\Fs\Layer;

/**
 * Handler for creation of the default .htaccess file
 *
 * @author gdever
 */
class Application
{

    /**
     * Method runs folder structure creation
     */
    public static function run(): void
    {

        $project_name = readline('Enter a name project: ');
        Layer::filePutContents(__DIR__ . "/../../../$project_name/Application.php", '<?php');
    }
}
```

**Comment by lolix-notepad** [comment]
## Question 2

```php
    /**
     * Creating folders on the disc
     *
     * @param string $path
     *            path to the file
     * @param bool $recursive
     *            use recursive directories
     * @return int result
     */
    public static function createDirectory(string $path, bool $recursive = false): int
    {
        if (Conf::getConfigValue('fs/layer', 'real') === 'real') {
            // @codeCoverageIgnoreStart
            return mkdir("../../$path", 0777, $recursive);
            // @codeCoverageIgnoreEnd
        }
    }
```

Can this be added in Mezon/Fs/Layer.php?
Because, to create the basic structure folder I need a function for it, or can I just use mkdir() in the Entity?

```php
<?php
namespace Mezon\Cli\Entities;

use Mezon\Fs\Layer;

/**
 * Handler for creation of the default .htaccess file
 *
 * @author gdever
 */
class Fs
{

    /**
     * Method runs folder structure creation
     */
    public static function run(): void
    {
        mkdir("../../Actions");
        mkdir("../../ListBuilderAdapters");

        // and so on...

        // or
        Layer::createDirectory("/Actions");
        Layer::createDirectory("/ListBuilderAdapters");
    }
}
```

**Comment by alexdodonov** [comment]
@lolix-notepad Hi!
Let's leave `Application.php` empty for now.

I have also created createDirectory method in the Mezon/Fs/Layer, so please check version 1.0.7 
But be carefull - it a little veries from your realization.

**Comment by alexdodonov** [comment]
@lolix-notepad don't worry. Your help is priceless )

**Comment by lolix-notepad** [comment]
Hello @alexdodonov.

I have some questions.

1. How to handle if a file already exists?

I have this example:

```php
        $file = getcwd() . '/.env';
        if (Layer::fileExists($file)) {
            echo "WARNING: file .env already exists.\n";
            $confirm = readline('Do you want override it? (y/n) ');
            if ($confirm === 'n')
                return;
        }
```

But I don't know if that is ok.

2. How the CLI is called?

When I install the mezon framework the CLI is in the vendor folder, so what is the best way to call the CLI?

**Comment by alexdodonov** [comment]
> I have this example:

It looks fine. But try to find out how to avoid code duplication, because you have almost the same code in `Entities/Application.php` and `Entities/Htaccess.php`

> When I install the mezon framework the CLI is in the vendor folder, so what is the best way to call the CLI?

I think it will be better to place `mezon` CLI script in the root folder of the project, but I still don't know how to do it.

I have tryed 'post-update-cmd' and 'post-install-cmd' scripts of the composer but it does not work properly.

**Comment by lolix-notepad** [comment]
> I think it will be better to place `mezon` CLI script in the root folder of the project, but I still don't know how to do it.
> 
> I have tryed 'post-update-cmd' and 'post-install-cmd' scripts of the composer but it does not work properly.

I have two proposals:

1. Add the mezon script to the mezon framework and the script internally calls mezon/cli.
2. Make mezon/cli a global package and then with 'mezon create project' the CLI creates a .env and also runs 'composer require mezon/mezon'.

**Comment by alexdodonov** [comment]
I think we need to create requirements to the CLI script.

First, as CLI script is a development tool, it must be installed only in developer environments, i.e. via require-dev secrion in composer.json. But I feel a lack of knowledge about global packages. May be this way will be fine.
Second, CLI script must be accessible with minimum amount of steps.
Third, it must work fine in *nix and win operational systems.

Looks like that your idea with global package better fits these requirements.

**Comment by alexdodonov** [comment]
May be this will help - https://getcomposer.org/doc/articles/vendor-binaries.md
Lots of packages are using it - phpunit, phpdoc, infection and others.
I think we should do the same.

**Comment by alexdodonov** [comment]
And looks like this 
> May be this will help - https://getcomposer.org/doc/articles/vendor-binaries.md

can be combined with this:

> Become mezon/cli into a global package and then with mezon create project the CLI creates a .env and also runs composer require mezon/mezon. Reference: https://github.com/lolix-notepad/mezon-cli/tree/make-cli-global

**Comment by lolix-notepad** [comment]
> And looks like this
> 
> > May be this will help - https://getcomposer.org/doc/articles/vendor-binaries.md
> 
> can be combined with this:
> 
> > Become mezon/cli into a global package and then with mezon create project the CLI creates a .env and also runs composer require mezon/mezon. Reference: https://github.com/lolix-notepad/mezon-cli/tree/make-cli-global

I have implemented your suggestions in the last pull request. #9

**Comment by alexdodonov** [comment]
@lolix-notepad good job!
